name: Azure Static Web Apps CI/CD

on:
    push:
        branches:
            - master
            - develop
            - non3D
            - electron-app
    pull_request:
        types: [closed]
        branches:
            - master

jobs:
    build_and_deploy_web_app_job:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest

        name: Build and Deploy Job
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_GROUND_0C9103F03 }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  action: 'upload'
                  app_location: '/dist' # App source code path
                  output_location: '' # Built app content directory - optional
                  production_branch: 'master'
                  skip_app_build: true

    build_and_deploy_electron_app_job:
        strategy:
            matrix:
                os: [{ name: 'windows', image: 'windows-latest' }, { name: 'macos', image: 'macos-latest' }]
        runs-on: ${{ matrix.os.image }}
        steps:
            - name: Github checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Install dependencies
              run: python -m pip install --upgrade pip setuptools

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Download certificate file
              run: |
                  echo $APPLE_DEVELOPER_ID_FILE | base64 --decode >> developer-id.p12
              if: matrix.os == 'macos-latest'
              shell: bash
              env:
                  APPLE_DEVELOPER_ID_FILE: ${{secrets.BCCM_APPLE_DEVELOPER_ID_FILE}}

            - name: Build for production
              run: npm run build:electron

            - name: Building the Electron app for Mac
              run: npm run package
              if: matrix.os == 'macos-latest'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CSC_LINK: developer-id.p12
                  CSC_KEY_PASSWORD: ${{secrets.BCCM_APPLE_DEVELOPER_ID_PASSWORD}}
                  APPLE_APP_SPECIFIC_PASSWORD: ${{secrets.BCCM_APPLE_APP_SPECIFIC_PASSWORD}}
                  APPLE_ID: ${{secrets.BCCM_APPLE_ID_USERNAME}}
                  APPLE_ID_PASSWORD: ${{secrets.BCCM_APPLE_APP_SPECIFIC_PASSWORD}}
                  APPLE_TEAM_ID: KJ6LCYQ3A8

            - name: Building the Electron app for Windows
              run: npm run package
              if: matrix.os != 'macos-latest'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: app
                  path: |
                      dist-app/Bible-Explorers*

    close_pull_request_job:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_GROUND_0C9103F03 }}
                  action: 'close'
                  production_branch: 'master'
